<?php

namespace Drupal\playground_form\Form;


use Drupal\Core\Form\FormStateInterface;
use Drupal\user\ProfileForm;

class NewProfileForm extends ProfileForm {
  /**
   * @inheritDoc
   */
  protected function actions(array $form, FormStateInterface $form_state) {
    return parent::actions($form, $form_state); // TODO: Change the autogenerated stub
  }
}
